# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94b17c7b1d187295804d075bdc009ed2a8cea30578ec3fd64c850fdc13d063535e48a6ba6dcc8a66ba75881ca13da86d897984fd67bb78747bf614ec4340bc4f

test:
  secret_key_base: 457f68f0acf3ba2aa87a7983ce82bbccd21ec2f939c6d2c64a24176cc50217b99151d92ccba30c90a96a360f3b7f361f29166df804791e91e121d2c5d0899b90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
